Solved a problem when launched with no options.

diff --git a/bin/git-last-commit b/bin/git-last-commit
--- a/bin/git-last-commit
+++ b/bin/git-last-commit
@@ -1,16 +1,20 @@
 #!/bin/bash
 
+source git-tools
+
+check_git_dir
+
 function usage {
 	echo "$(basename $0) - Utility to view the last commit id."
 	echo "Usage: $(basename $0) [option [option...]]"
 	echo "Options:"
-	echo "  commit: Shows the last commit."
-	echo "  abbr  : Shows abbreviated last commit."
-	echo "  date  : Shows last commit date."
-	echo "  help  : Shows this help."
+	echo "  -c|--commit: Shows the last commit."
+	echo "  -a|--abbr  : Shows abbreviated last commit."
+	echo "  -d|--date  : Shows last commit date."
+	echo "  -h         : Shows this help."
 	echo "Example:"
-	echo "  Command 'git last-commit abbr date' will show:"
-	echo -n "  1667ca5 2014-02-19 18:09:56 +0100"
+	echo "  Command 'git last-commit --abbr --date' will show:"
+	echo "  1667ca5 2014-02-19 18:09:56 +0100"
 }
 
 function last_commit {
@@ -25,25 +29,31 @@ function last_commit_date {
 	git show -s --format=%ci "$1" | tr -d '\n'
 }
 
-for param in $@; do
-	case "$param" in
-		commit)
-			last_commit
-		;;
-		abbr)
-			last_commit_abbr
-		;;
-		date)
-			last_commit_date $(last_commit)
-		;;
-		help)
-			usage
-		;;
-		*)
-			last_commit
-		;;
-	esac
-	echo -n " "
-done
+if [ $# != 0 ]; then
+	for param in $@; do
+		case "$param" in
+			-c|--commit)
+				last_commit
+			;;
+			-a|--abbr)
+				last_commit_abbr
+			;;
+			-d|--date)
+				last_commit_date $(last_commit)
+			;;
+			-h)
+				usage
+				exit 0
+			;;
+			*)
+				echo "ERROR: Invalid option: $param"
+				exit 1
+			;;
+		esac
+		echo -n " "
+	done
+else
+	last_commit
+fi
 
 echo
