Refactor main functionality
* Add function to check if a branch exists.
* Refactor try code into a function.
* Create a main function with argument checking.

diff --git a/bin/git-try-merge b/bin/git-try-merge
--- a/bin/git-try-merge
+++ b/bin/git-try-merge
@@ -3,6 +3,8 @@
 # More information:
 # http://stackoverflow.com/questions/6335717/can-git-tell-me-if-a-merge-will-conflict-without-actually-merging
 
+SHOW_DIFF=
+
 function error() {
 	echo "ERROR: $*" 1>&2
 }
@@ -17,7 +19,51 @@ function help() {
 	exit 1
 }
 
-git format-patch ..$1 --stdout | git apply --check - 2>/dev/null
-ret=$?
-git diff $1
-exit $ret
+function branchExists() {
+	git rev-parse --verify "$1" >/dev/null 2>&1
+}
+
+function tryMerge() {
+	git format-patch ..$1 --stdout | git apply --check - 2>/dev/null
+	ret=$?
+	if [ -n "$SHOW_DIFF" ]; then
+		git diff $1
+	fi
+	exit $ret
+}
+
+function main() {
+	if [ $# == 0 ]; then
+		help
+	fi
+
+	while getopts ":hd" opt; do
+		case "$opt" in
+			h)
+				help
+			;;
+			d)
+				SHOW_DIFF=yes
+				shift
+			;;
+			\?)
+				error "Invalid option: -$OPTARG"
+				exit 2
+			;;
+		esac
+	done
+
+	if [ $# -ne 1 ]; then
+		error "Must specify only one branch."
+		exit 3
+	fi
+
+	if ! branchExists "$1"; then
+		error "Branch does not exist: $1"
+		exit 4
+	fi
+
+	tryMerge "$1"
+}
+
+main "$@"
